const contacts = [
  {
    id: 9,
    title: `APPLE iphone 14 (Blue,128GB)`,
    rating: `4.3`,
    price: `67,999`,
    category: `men`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/l0e6kcw0/t-shirt/h/g/d/m-half-triangel-black-one-nb-nicky-boy-original-imagc747apzffz5q.jpeg?q=70`,
  },
  {
    id: 10,
    title: `APPLE iphone 14 (Blue,128GB)`,
    rating: `4.3`,
    price: `67,999`,
    category: `men`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/3/2/s/m-t2-m6-autna-original-imaggqvx5ycshdbx.jpeg?q=70`,
  },
  {
    id: 11,
    title: `APPLE iphone 14 (Blue,128GB)`,
    rating: `4.3`,
    price: `67,999`,
    category: `men`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/d/t/7/l-tblrnful-d108-tripr-original-imags8h2bz3gkmh2.jpeg?q=70`,
  },
  {
    id: 12,
    title: `APPLE iphone 14 (Blue,128GB)`,
    rating: `4.3`,
    price: `67,999`,
    category: `men`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/z/0/k/l-all-rbcpon-sky-one-nb-nicky-boy-original-imagrdhcgyk7papf.jpeg?q=70`,
  },
  {
    id: 13,
    title: `APPLE iphone 14 (Blue,128GB)`,
    rating: `4.3`,
    price: `67,999`,
    category: `men`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/i/b/g/s-half-triangel-black-one-nb-nicky-boy-original-imagmhzyv6b64vfb.jpeg?q=70`,
  },
  {
    id: 14,
    title: `APPLE iphone 14 (Blue,128GB)`,
    rating: `4.3`,
    price: `67,999`,
    category: `men`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/4/t/i/xxl-ausk0179-ausk-original-imagmffbcvcxu9gf.jpeg?q=70`,
  },
  {
    id: 15,
    title: `APPLE iphone 14 (Blue,128GB)`,
    rating: `4.3`,
    price: `67,999`,
    category: `men`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/7/n/u/l-half-carnival-one-nb-nicky-boy-original-imagghqmtwkgkc8f.jpeg?q=70`,
  },
  {
    id: 16,
    title: `APPLE iphone 14 (Blue,128GB)`,
    rating: `4.3`,
    price: `67,999`,
    category: `men`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/7/e/c/l-oversizetsrt-101-kajaru-original-imagrk3shy733gyp.jpeg?q=70`,
  },
  {
    id: 17,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/l4oi4cw0/lehenga-choli/b/z/l/free-sleeveless-fidera-organza-fabcartz-original-imagfgrsk8rz92aq.jpeg?q=70`,
    rating: `4.3`,
    category: `women`,
    price: `67,999`,
  },

  {
    id: 18,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/lehenga-choli/y/l/v/free-half-sleeve-rc-2-anara-purple-work-lehenga-choli-toriox-original-imaghyzcsfddvtkv.jpeg?q=70`,
    rating: `4.3`,
    category: `women`,
    price: `67,999`,
  },
  {
    id: 19,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/ks0onm80/lehenga-choli/l/w/5/free-sleeveless-bindu-lehenga-color-bucket-original-imag5zhbd7vutanw.jpeg?q=70`,
    rating: `4.3`,
    category: `women`,
    price: `67,999`,
  },
  {
    id: 20,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/lehenga-choli/6/c/t/free-short-sleeve-dream-zinariya-fab-original-imaghezwnzgg9hyj.jpeg?q=70`,
    rating: `4.3`,
    category: `women`,
    price: `67,999`,
  },
  {
    id: 21,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/l2arp8w0/lehenga-choli/x/d/7/free-sleeveless-bindu-lehenga-color-bucket-original-imagdzabduyfugfn.jpeg?q=70`,
    rating: `4.3`,
    category: `women`,
    price: `67,999`,
  },
  {
    id: 22,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/ks99aq80/lehenga-choli/y/m/b/free-sleeveless-bindu-lehenga-color-bucket-original-imag5uz7kzjkzfrj.jpeg?q=70`,
    rating: `4.3`,
    category: `women`,
    price: `67,999`,
  },
  {
    id: 23,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/l2arp8w0/lehenga-choli/5/l/v/free-sleeveless-bindu-lehenga-color-bucket-original-imagdzaazdtvfubs.jpeg?q=70`,
    rating: `4.3`,
    category: `women`,
    price: `67,999`,
  },
  {
    id: 24,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/lehenga-choli/l/x/d/free-full-sleeve-lehenga-lehenga-for-women-lehenga-choli-net-original-imaggcwfb3pjh2hf.jpeg?q=70`,
    rating: `4.3`,
    category: `women`,
    price: `67,999`,
  },
  {
    id: 25,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/v/f/r/-original-imagrgypagzeskps.jpeg?q=70`,
    rating: `4.3`,
    price: `67,999`,
    category: `smart watch`,
  },
  {
    id: 26,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/r/x/h/-original-imagrgyzpz67ngcr.jpeg?q=70`,
    rating: `4.3`,
    price: `67,999`,
    category: `smart watch`,
  },
  {
    id: 27,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/l3ahpjk0/smartwatch/c/w/8/-original-imagegyhw5gemgnv.jpeg?q=70`,
    rating: `4.3`,
    price: `67,999`,
    category: `smart watch`,
  },
  {
    id: 28,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/q/4/2/-original-imaggstrsxtwxzar.jpeg?q=70`,
    rating: `4.3`,
    price: `67,999`,
    category: `smart watch`,
  },
  {
    id: 29,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/h/m/q/-original-imagsgdxtkjgjfxa.jpeg?q=70`,
    rating: `4.3`,
    price: `67,999`,
    category: `smart watch`,
  },
  {
    id: 30,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/i/r/x/-original-imagq9hbxdftyzzc.jpeg?q=70`,
    rating: `4.3`,
    price: `67,999`,
    category: `smart watch`,
  },
  {
    id: 31,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/l/w/d/-original-imaghkppxxzfua2r.jpeg?q=70`,
    rating: `4.3`,
    price: `67,999`,
    category: `smart watch`,
  },
  {
    id: 32,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/q/t/f/-original-imagqtnhgfjkbvz5.jpeg?q=70`,
    rating: `4.3`,
    price: `67,999`,
    category: `smart watch`,
  },
  {
    id: 33,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/l/r/v/10-369573-10-puma-parisian-night-high-risk-red-white-original-imaghbgnufgqtrgt.jpeg?q=70`,
    rating: `4.3`,
    category: `sneakers`,
    price: `67,999`,
  },
  {
    id: 34,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/r/f/5/11-2531910312-11-u-s-polo-assn-off-white-original-imags5qhjgh9sgq2.jpeg?q=70`,
    rating: `4.3`,
    category: `sneakers`,
    price: `67,999`,
  },
  {
    id: 35,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/r/8/9/-original-imagzry3gqhhdad2.jpeg?q=70`,
    rating: `4.3`,
    category: `sneakers`,
    price: `67,999`,
  },
  {
    id: 36,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/j/w/m/9-thunder-01-9-asian-magic-white-original-imagsawbyjaqheae.jpeg?q=70`,
    rating: `4.3`,
    category: `sneakers`,
    price: `67,999`,
  },
  {
    id: 37,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/o/9/5/-original-imagrg6gty9fajrx.jpeg?q=70`,
    rating: `4.3`,
    category: `sneakers`,
    price: `67,999`,
  },
  {
    id: 38,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/l/i/h/10-tarzan-04-10-asian-white-navy-grey-original-imagrvffnzeugzgh.jpeg?q=70`,
    rating: `4.3`,
    category: `sneakers`,
    price: `67,999`,
  },
  {
    id: 39,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/u/x/d/-original-imaggcay6d5jwkw9.jpeg?q=70`,
    rating: `4.3`,
    category: `sneakers`,
    price: `67,999`,
  },
  {
    id: 40,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/k/l/v/6-pc-jr-6-airson-white-original-imagnwy4c6gmyrqu.jpeg?q=70`,
    rating: `4.3`,
    category: `sneakers`,
    price: `67,999`,
  },

  {
    id: 11,
    title: `APPLE iphone 14 (Blue,128GB)`,
    thumbnail: `https://rukminim2.flixcart.com/image/312/312/krntoy80/television/t/b/d/a-3200n-adsun-original-imag5ecyt6ystkrv.jpeg?q=70`,
    rating: `4.3`,
    price: `67,999`,
    category: `tv`,
  },
  {
    id: 9,
    title: "iPhone 9",
    description: "An apple smartphones which is nothing like apple",
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "https://cdn.dummyjson.com/product-images/1/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/1/1.jpg",
      "https://cdn.dummyjson.com/product-images/1/2.jpg",
      "https://cdn.dummyjson.com/product-images/1/3.jpg",
      "https://cdn.dummyjson.com/product-images/1/4.jpg",
      "https://cdn.dummyjson.com/product-images/1/thumbnail.jpg",
    ],
  },
  {
    id: 10,
    title: "iPhone X",
    description:
      "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
    price: 899,
    discountPercentage: 17.94,
    rating: 4.44,
    stock: 34,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "https://cdn.dummyjson.com/product-images/2/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/2/1.jpg",
      "https://cdn.dummyjson.com/product-images/2/2.jpg",
      "https://cdn.dummyjson.com/product-images/2/3.jpg",
      "https://cdn.dummyjson.com/product-images/2/thumbnail.jpg",
    ],
  },
  {
    id: 11,
    title: "Samsung Universe 9",
    description:
      "Samsung's new variant which goes beyond Galaxy to the Universe",
    price: 1249,
    discountPercentage: 15.46,
    rating: 4.09,
    stock: 36,
    brand: "Samsung",
    category: "smartphones",
    thumbnail: "https://cdn.dummyjson.com/product-images/3/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/3/1.jpg"],
  },
  {
    id: 12,
    title: "OPPOF19",
    description: "OPPO F19 is officially announced on April 2021.",
    price: 280,
    discountPercentage: 17.91,
    rating: 4.3,
    stock: 123,
    brand: "OPPO",
    category: "smartphones",
    thumbnail: "https://cdn.dummyjson.com/product-images/4/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/4/1.jpg",
      "https://cdn.dummyjson.com/product-images/4/2.jpg",
      "https://cdn.dummyjson.com/product-images/4/3.jpg",
      "https://cdn.dummyjson.com/product-images/4/4.jpg",
      "https://cdn.dummyjson.com/product-images/4/thumbnail.jpg",
    ],
  },
  {
    id: 13,
    title: "Huawei P30",
    description:
      "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
    price: 499,
    discountPercentage: 10.58,
    rating: 4.09,
    stock: 32,
    brand: "Huawei",
    category: "smartphones",
    thumbnail: "https://cdn.dummyjson.com/product-images/5/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/5/1.jpg",
      "https://cdn.dummyjson.com/product-images/5/2.jpg",
      "https://cdn.dummyjson.com/product-images/5/3.jpg",
    ],
  },
  {
    id: 14,
    title: "MacBook Pro",
    description:
      "MacBook Pro 2021 with mini-LED display may launch between September, November",
    price: 1749,
    discountPercentage: 11.02,
    rating: 4.57,
    stock: 83,
    brand: "Apple",
    category: "laptops",
    thumbnail: "https://cdn.dummyjson.com/product-images/6/thumbnail.png",
    images: [
      "https://cdn.dummyjson.com/product-images/6/1.png",
      "https://cdn.dummyjson.com/product-images/6/2.jpg",
      "https://cdn.dummyjson.com/product-images/6/3.png",
      "https://cdn.dummyjson.com/product-images/6/4.jpg",
    ],
  },
  {
    id: 15,
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: "Samsung",
    category: "laptops",
    thumbnail: "https://cdn.dummyjson.com/product-images/7/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/7/1.jpg",
      "https://cdn.dummyjson.com/product-images/7/2.jpg",
      "https://cdn.dummyjson.com/product-images/7/3.jpg",
      "https://cdn.dummyjson.com/product-images/7/thumbnail.jpg",
    ],
  },
  {
    id: 16,
    title: "Microsoft Surface Laptop 4",
    description:
      "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
    price: 1499,
    discountPercentage: 10.23,
    rating: 4.43,
    stock: 68,
    brand: "Microsoft Surface",
    category: "laptops",
    thumbnail: "https://cdn.dummyjson.com/product-images/8/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/8/1.jpg",
      "https://cdn.dummyjson.com/product-images/8/2.jpg",
      "https://cdn.dummyjson.com/product-images/8/3.jpg",
      "https://cdn.dummyjson.com/product-images/8/4.jpg",
      "https://cdn.dummyjson.com/product-images/8/thumbnail.jpg",
    ],
  },
  {
    id: 17,
    title: "Infinix INBOOK",
    description:
      "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
    price: 1099,
    discountPercentage: 11.83,
    rating: 4.54,
    stock: 96,
    brand: "Infinix",
    category: "laptops",
    thumbnail: "https://cdn.dummyjson.com/product-images/9/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/9/1.jpg",
      "https://cdn.dummyjson.com/product-images/9/2.png",
      "https://cdn.dummyjson.com/product-images/9/3.png",
      "https://cdn.dummyjson.com/product-images/9/4.jpg",
      "https://cdn.dummyjson.com/product-images/9/thumbnail.jpg",
    ],
  },
  {
    id: 18,
    title: "HP Pavilion 15-DK1056WM",
    description:
      "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
    price: 1099,
    discountPercentage: 6.18,
    rating: 4.43,
    stock: 89,
    brand: "HP Pavilion",
    category: "laptops",
    thumbnail: "https://cdn.dummyjson.com/product-images/10/thumbnail.jpeg",
    images: [
      "https://cdn.dummyjson.com/product-images/10/1.jpg",
      "https://cdn.dummyjson.com/product-images/10/2.jpg",
      "https://cdn.dummyjson.com/product-images/10/3.jpg",
      "https://cdn.dummyjson.com/product-images/10/thumbnail.jpeg",
    ],
  },
  {
    id: 41,
    title: "NIGHT SUIT",
    description: "NIGHT SUIT RED MICKY MOUSE..  For Girls. Fantastic Suits.",
    price: 55,
    discountPercentage: 15.05,
    rating: 4.65,
    stock: 21,
    brand: "RED MICKY MOUSE..",
    category: `women`,
    thumbnail: "https://cdn.dummyjson.com/product-images/41/thumbnail.webp",
    images: [
      "https://cdn.dummyjson.com/product-images/41/1.jpg",
      "https://cdn.dummyjson.com/product-images/41/2.webp",
      "https://cdn.dummyjson.com/product-images/41/3.jpg",
      "https://cdn.dummyjson.com/product-images/41/4.jpg",
      "https://cdn.dummyjson.com/product-images/41/thumbnail.webp",
    ],
  },
  {
    id: 42,
    title: "Stiched Kurta plus trouser",
    description:
      "FABRIC: LILEIN CHEST: 21 LENGHT: 37 TROUSER: (38) :ARABIC LILEIN",
    price: 80,
    discountPercentage: 15.37,
    rating: 4.05,
    stock: 148,
    brand: "Digital Printed",
    category: `women`,
    thumbnail: "https://cdn.dummyjson.com/product-images/42/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/42/1.png",
      "https://cdn.dummyjson.com/product-images/42/2.png",
      "https://cdn.dummyjson.com/product-images/42/3.png",
      "https://cdn.dummyjson.com/product-images/42/4.jpg",
      "https://cdn.dummyjson.com/product-images/42/thumbnail.jpg",
    ],
  },
  {
    id: 43,
    title: "frock gold printed",
    description:
      "Ghazi fabric long frock gold printed ready to wear stitched collection (G992)",
    price: 600,
    discountPercentage: 15.55,
    rating: 4.31,
    stock: 150,
    brand: "Ghazi Fabric",
    category: `women`,
    thumbnail: "https://cdn.dummyjson.com/product-images/43/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/43/1.jpg",
      "https://cdn.dummyjson.com/product-images/43/2.jpg",
      "https://cdn.dummyjson.com/product-images/43/3.jpg",
      "https://cdn.dummyjson.com/product-images/43/4.jpg",
      "https://cdn.dummyjson.com/product-images/43/thumbnail.jpg",
    ],
  },
  {
    id: 44,
    title: "Ladies Multicolored Dress",
    description:
      "This classy shirt for women gives you a gorgeous look on everyday wear and specially for semi-casual wears.",
    price: 79,
    discountPercentage: 16.88,
    rating: 4.03,
    stock: 2,
    brand: "Ghazi Fabric",
    category: `women`,
    thumbnail: "https://cdn.dummyjson.com/product-images/44/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/44/1.jpg",
      "https://cdn.dummyjson.com/product-images/44/2.jpg",
      "https://cdn.dummyjson.com/product-images/44/3.jpg",
      "https://cdn.dummyjson.com/product-images/44/4.jpg",
      "https://cdn.dummyjson.com/product-images/44/thumbnail.jpg",
    ],
  },
  {
    id: 45,
    title: "Malai Maxi Dress",
    description:
      "Ready to wear, Unique design according to modern standard fashion, Best fitting ,Imported stuff",
    price: 50,
    discountPercentage: 5.07,
    rating: 4.67,
    stock: 96,
    brand: "IELGY",
    category: `women`,
    thumbnail: "https://cdn.dummyjson.com/product-images/45/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/45/1.jpg",
      "https://cdn.dummyjson.com/product-images/45/2.webp",
      "https://cdn.dummyjson.com/product-images/45/3.jpg",
      "https://cdn.dummyjson.com/product-images/45/4.jpg",
      "https://cdn.dummyjson.com/product-images/45/thumbnail.jpg",
    ],
  },
  {
    id: 51,
    title: "half sleeves T shirts",
    description:
      "Many store is creating new designs and trend every month and every year. Daraz.pk have a beautiful range of men fashion brands",
    price: 23,
    discountPercentage: 12.76,
    rating: 4.26,
    stock: 132,
    brand: "Vintage Apparel",
    category: "men",
    thumbnail: "https://cdn.dummyjson.com/product-images/51/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/51/1.png",
      "https://cdn.dummyjson.com/product-images/51/2.jpg",
      "https://cdn.dummyjson.com/product-images/51/3.jpg",
      "https://cdn.dummyjson.com/product-images/51/thumbnail.jpg",
    ],
  },
  {
    id: 52,
    title: "FREE FIRE T Shirt",
    description:
      "quality and professional print - It doesn't just look high quality, it is high quality.",
    price: 10,
    discountPercentage: 14.72,
    rating: 4.52,
    stock: 128,
    brand: "FREE FIRE",
    category: "men",
    thumbnail: "https://cdn.dummyjson.com/product-images/52/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/52/1.png",
      "https://cdn.dummyjson.com/product-images/52/2.png",
      "https://cdn.dummyjson.com/product-images/52/3.jpg",
      "https://cdn.dummyjson.com/product-images/52/4.jpg",
      "https://cdn.dummyjson.com/product-images/52/thumbnail.jpg",
    ],
  },
  {
    id: 53,
    title: "printed high quality T shirts",
    description: "Brand: vintage Apparel ,Export quality",
    price: 35,
    discountPercentage: 7.54,
    rating: 4.89,
    stock: 6,
    brand: "Vintage Apparel",
    category: "men",
    thumbnail: "https://cdn.dummyjson.com/product-images/53/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/53/1.webp",
      "https://cdn.dummyjson.com/product-images/53/2.jpg",
      "https://cdn.dummyjson.com/product-images/53/3.jpg",
      "https://cdn.dummyjson.com/product-images/53/4.jpg",
      "https://cdn.dummyjson.com/product-images/53/thumbnail.jpg",
    ],
  },
  {
    id: 54,
    title: "Pubg Printed Graphic T-Shirt",
    description:
      "Product Description Features: 100% Ultra soft Polyester Jersey. Vibrant & colorful printing on front. Feels soft as cotton without ever cracking",
    price: 46,
    discountPercentage: 16.44,
    rating: 4.62,
    stock: 136,
    brand: "The Warehouse",
    category: "men",
    thumbnail: "https://cdn.dummyjson.com/product-images/54/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/54/1.jpg",
      "https://cdn.dummyjson.com/product-images/54/2.jpg",
      "https://cdn.dummyjson.com/product-images/54/3.jpg",
      "https://cdn.dummyjson.com/product-images/54/4.jpg",
      "https://cdn.dummyjson.com/product-images/54/thumbnail.jpg",
    ],
  },
  {
    id: 55,
    title: "Money Heist Printed Summer T Shirts",
    description: "Fabric Jercy, Size: M & L Wear Stylish Dual Stiched",
    price: 66,
    discountPercentage: 15.97,
    rating: 4.9,
    stock: 122,
    brand: "The Warehouse",
    category: "men",
    thumbnail: "https://cdn.dummyjson.com/product-images/55/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/55/1.jpg",
      "https://cdn.dummyjson.com/product-images/55/2.webp",
      "https://cdn.dummyjson.com/product-images/55/3.jpg",
      "https://cdn.dummyjson.com/product-images/55/4.jpg",
      "https://cdn.dummyjson.com/product-images/55/thumbnail.jpg",
    ],
  },
  {
    id: 56,
    title: "Sneakers Joggers Shoes",
    description:
      "Gender: Men , Colors: Same as DisplayedCondition: 100% Brand New",
    price: 40,
    discountPercentage: 12.57,
    rating: 4.38,
    stock: 6,
    brand: "Sneakers",
    category: "mens-shoes",
    thumbnail: "https://cdn.dummyjson.com/product-images/56/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/56/1.jpg",
      "https://cdn.dummyjson.com/product-images/56/2.jpg",
      "https://cdn.dummyjson.com/product-images/56/3.jpg",
      "https://cdn.dummyjson.com/product-images/56/4.jpg",
      "https://cdn.dummyjson.com/product-images/56/5.jpg",
      "https://cdn.dummyjson.com/product-images/56/thumbnail.jpg",
    ],
  },
  {
    id: 57,
    title: "Loafers for men",
    description:
      "Men Shoes - Loafers for men - Rubber Shoes - Nylon Shoes - Shoes for men - Moccassion - Pure Nylon (Rubber) Expot Quality.",
    price: 47,
    discountPercentage: 10.91,
    rating: 4.91,
    stock: 20,
    brand: "Rubber",
    category: "mens-shoes",
    thumbnail: "https://cdn.dummyjson.com/product-images/57/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/57/1.jpg",
      "https://cdn.dummyjson.com/product-images/57/2.jpg",
      "https://cdn.dummyjson.com/product-images/57/3.jpg",
      "https://cdn.dummyjson.com/product-images/57/4.jpg",
      "https://cdn.dummyjson.com/product-images/57/thumbnail.jpg",
    ],
  },
  {
    id: 58,
    title: "formal offices shoes",
    description:
      "Pattern Type: Solid, Material: PU, Toe Shape: Pointed Toe ,Outsole Material: Rubber",
    price: 57,
    discountPercentage: 12,
    rating: 4.41,
    stock: 68,
    brand: "The Warehouse",
    category: "mens-shoes",
    thumbnail: "https://cdn.dummyjson.com/product-images/58/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/58/1.jpg",
      "https://cdn.dummyjson.com/product-images/58/2.jpg",
      "https://cdn.dummyjson.com/product-images/58/3.jpg",
      "https://cdn.dummyjson.com/product-images/58/4.jpg",
      "https://cdn.dummyjson.com/product-images/58/thumbnail.jpg",
    ],
  },
  {
    id: 59,
    title: "Spring and summershoes",
    description:
      "Comfortable stretch cloth, lightweight body; ,rubber sole, anti-skid wear;",
    price: 20,
    discountPercentage: 8.71,
    rating: 4.33,
    stock: 137,
    brand: "Sneakers",
    category: "mens-shoes",
    thumbnail: "https://cdn.dummyjson.com/product-images/59/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/59/1.jpg",
      "https://cdn.dummyjson.com/product-images/59/2.jpg",
      "https://cdn.dummyjson.com/product-images/59/3.jpg",
      "https://cdn.dummyjson.com/product-images/59/4.jpg",
      "https://cdn.dummyjson.com/product-images/59/thumbnail.jpg",
    ],
  },
  {
    id: 60,
    title: "Stylish Casual Jeans Shoes",
    description:
      "High Quality ,Stylish design ,Comfortable wear ,FAshion ,Durable",
    price: 58,
    discountPercentage: 7.55,
    rating: 4.55,
    stock: 129,
    brand: "Sneakers",
    category: "mens-shoes",
    thumbnail: "https://cdn.dummyjson.com/product-images/60/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/60/1.jpg",
      "https://cdn.dummyjson.com/product-images/60/2.jpg",
      "https://cdn.dummyjson.com/product-images/60/3.jpg",
      "https://cdn.dummyjson.com/product-images/60/thumbnail.jpg",
    ],
  },
  {
    id: 61,
    title: "Leather Straps Wristwatch",
    description: "Style:Sport ,Clasp:Buckles ,Water Resistance Depth:3Bar",
    price: 120,
    discountPercentage: 7.14,
    rating: 4.63,
    stock: 91,
    brand: "Naviforce",
    category: "mens-watches",
    thumbnail: "https://cdn.dummyjson.com/product-images/61/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/61/1.jpg",
      "https://cdn.dummyjson.com/product-images/61/2.png",
      "https://cdn.dummyjson.com/product-images/61/3.jpg",
    ],
  },
  {
    id: 62,
    title: "Waterproof Leather Brand Watch",
    description:
      "Watch Crown With Environmental IPS Bronze Electroplating; Display system of 12 hours",
    price: 46,
    discountPercentage: 3.15,
    rating: 4.05,
    stock: 95,
    brand: "SKMEI 9117",
    category: "mens-watches",
    thumbnail: "https://cdn.dummyjson.com/product-images/62/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/62/1.jpg",
      "https://cdn.dummyjson.com/product-images/62/2.jpg",
    ],
  },
  {
    id: 63,
    title: "Royal Blue Premium Watch",
    description:
      "Men Silver Chain Royal Blue Premium Watch Latest Analog Watch",
    price: 50,
    discountPercentage: 2.56,
    rating: 4.89,
    stock: 142,
    brand: "SKMEI 9117",
    category: "mens-watches",
    thumbnail: "https://cdn.dummyjson.com/product-images/63/thumbnail.webp",
    images: [
      "https://cdn.dummyjson.com/product-images/63/1.jpg",
      "https://cdn.dummyjson.com/product-images/63/2.jpg",
      "https://cdn.dummyjson.com/product-images/63/3.png",
      "https://cdn.dummyjson.com/product-images/63/4.jpeg",
    ],
  },
  {
    id: 64,
    title: "Leather Strap Skeleton Watch",
    description:
      "Leather Strap Skeleton Watch for Men - Stylish and Latest Design",
    price: 46,
    discountPercentage: 10.2,
    rating: 4.98,
    stock: 61,
    brand: "Strap Skeleton",
    category: "mens-watches",
    thumbnail: "https://cdn.dummyjson.com/product-images/64/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/64/1.jpg",
      "https://cdn.dummyjson.com/product-images/64/2.webp",
      "https://cdn.dummyjson.com/product-images/64/3.jpg",
      "https://cdn.dummyjson.com/product-images/64/thumbnail.jpg",
    ],
  },
  {
    id: 65,
    title: "Stainless Steel Wrist Watch",
    description:
      "Stylish Watch For Man (Luxury) Classy Men's Stainless Steel Wrist Watch - Box Packed",
    price: 47,
    discountPercentage: 17.79,
    rating: 4.79,
    stock: 94,
    brand: "Stainless",
    category: "mens-watches",
    thumbnail: "https://cdn.dummyjson.com/product-images/65/thumbnail.webp",
    images: [
      "https://cdn.dummyjson.com/product-images/65/1.jpg",
      "https://cdn.dummyjson.com/product-images/65/2.webp",
      "https://cdn.dummyjson.com/product-images/65/3.jpg",
      "https://cdn.dummyjson.com/product-images/65/4.webp",
      "https://cdn.dummyjson.com/product-images/65/thumbnail.webp",
    ],
  },
  {
    id: 46,
    title: "women's shoes",
    description:
      "Close: Lace, Style with bottom: Increased inside, Sole Material: Rubber",
    price: 40,
    discountPercentage: 16.96,
    rating: 4.14,
    stock: 72,
    brand: "IELGY fashion",
    category: "womens-shoes",
    thumbnail: "https://cdn.dummyjson.com/product-images/46/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/46/1.webp",
      "https://cdn.dummyjson.com/product-images/46/2.jpg",
      "https://cdn.dummyjson.com/product-images/46/3.jpg",
      "https://cdn.dummyjson.com/product-images/46/4.jpg",
      "https://cdn.dummyjson.com/product-images/46/thumbnail.jpg",
    ],
  },
  {
    id: 47,
    title: "Sneaker shoes",
    description:
      "Synthetic Leather Casual Sneaker shoes for Women/girls Sneakers For Women",
    price: 120,
    discountPercentage: 10.37,
    rating: 4.19,
    stock: 50,
    brand: "Synthetic Leather",
    category: "womens-shoes",
    thumbnail: "https://cdn.dummyjson.com/product-images/47/thumbnail.jpeg",
    images: [
      "https://cdn.dummyjson.com/product-images/47/1.jpg",
      "https://cdn.dummyjson.com/product-images/47/2.jpg",
      "https://cdn.dummyjson.com/product-images/47/3.jpg",
      "https://cdn.dummyjson.com/product-images/47/thumbnail.jpeg",
    ],
  },
  {
    id: 48,
    title: "Women Strip Heel",
    description:
      "Features: Flip-flops, Mid Heel, Comfortable, Striped Heel, Antiskid, Striped",
    price: 40,
    discountPercentage: 10.83,
    rating: 4.02,
    stock: 25,
    brand: "Sandals Flip Flops",
    category: "womens-shoes",
    thumbnail: "https://cdn.dummyjson.com/product-images/48/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/48/1.jpg",
      "https://cdn.dummyjson.com/product-images/48/2.jpg",
      "https://cdn.dummyjson.com/product-images/48/3.jpg",
      "https://cdn.dummyjson.com/product-images/48/4.jpg",
      "https://cdn.dummyjson.com/product-images/48/thumbnail.jpg",
    ],
  },
  {
    id: 49,
    title: "Chappals & Shoe Ladies Metallic",
    description:
      "Womens Chappals & Shoe Ladies Metallic Tong Thong Sandal Flat Summer 2020 Maasai Sandals",
    price: 23,
    discountPercentage: 2.62,
    rating: 4.72,
    stock: 107,
    brand: "Maasai Sandals",
    category: "womens-shoes",
    thumbnail: "https://cdn.dummyjson.com/product-images/49/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/49/1.jpg",
      "https://cdn.dummyjson.com/product-images/49/2.jpg",
      "https://cdn.dummyjson.com/product-images/49/3.webp",
      "https://cdn.dummyjson.com/product-images/49/thumbnail.jpg",
    ],
  },
  {
    id: 50,
    title: "Women Shoes",
    description:
      "2020 New Arrivals Genuine Leather Fashion Trend Platform Summer Women Shoes",
    price: 36,
    discountPercentage: 16.87,
    rating: 4.33,
    stock: 46,
    brand: "Arrivals Genuine",
    category: "womens-shoes",
    thumbnail: "https://cdn.dummyjson.com/product-images/50/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/50/1.jpeg",
      "https://cdn.dummyjson.com/product-images/50/2.jpg",
      "https://cdn.dummyjson.com/product-images/50/3.jpg",
    ],
  },
  // {
  //   id: 1,
  //   name: `APPLE iphone 14 (Blue,128GB)`,
  //   rating: `4.3`,
  //   price: `67,999`,
  //   category: `mobile`,
  //   src: `https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/4/g/o/11-5g-rmx3780-realme-original-imagsjx49ndppgxy.jpeg?q=70`,
  //   offer: `Available offers

  //       Bank Offer10% off on ICICI Bank Credit Card, up to ₹1250 on orders of ₹5,000 and aboveT&C

  //       Bank Offer10% off on Select ICICI Bank Credit Cards, up to ₹1250 on orders of ₹5,000 and aboveT&C

  //       Bank Offer10% off on Axis Bank and Citi Credit Card, up to ₹1250 on orders of ₹5,000 and aboveT&C

  //       Special PriceGet extra 22% off (price inclusive of cashback/coupon)T&C`,
  // },
  // {
  //   id: 2,
  //   name: `APPLE iphone 14 (Blue,128GB)`,
  //   rating: `4.3`,
  //   price: `67,999`,
  //   category: `mobile`,
  //   src: `https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/3/5/l/-original-imaghx9qmgqsk9s4.jpeg?q=70`,
  // },
  // {
  //   id: 3,
  //   name: `APPLE iphone 14 (Blue,128GB)`,
  //   rating: `4.3`,
  //   price: `67,999`,
  //   category: `mobile`,
  //   src: `https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/r/o/o/-original-imaghkvuzxkcna4n.jpeg?q=70`,
  // },
  // {
  //   id: 4,
  //   name: `APPLE iphone 14 (Blue,128GB)`,
  //   rating: `4.3`,
  //   price: `67,999`,
  //   category: `mobile`,
  //   src: `https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/x/7/p/-original-imagr9y5a3qdkkge.jpeg?q=70`,
  // },
  // {
  //   id: 5,
  //   name: `APPLE iphone 14 (Blue,128GB)`,
  //   rating: `4.3`,
  //   price: `67,999`,
  //   category: `mobile`,
  //   src: `https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/h/o/e/-original-imagstfsbhaaxbeb.jpeg?q=70`,
  // },
  // {
  //   id: 6,
  //   name: `APPLE iphone 14 (Blue,128GB)`,
  //   rating: `4.3`,
  //   price: `67,999`,
  //   category: `mobile`,
  //   src: `https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/v/f/d/-original-imagpgx4g2m63gfh.jpeg?q=70`,
  // },
  // {
  //   id: 7,
  //   name: `APPLE iphone 14 (Blue,128GB)`,
  //   rating: `4.3`,
  //   price: `67,999`,
  //   category: `mobile`,
  //   src: `https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/q/t/h/galaxy-f54-5g-sm-e546bzshins-samsung-original-imagq79f82pfyzvh.jpeg?q=70`,
  // },
  // {
  //   id: 8,
  //   name: `APPLE iphone 14 (Blue,128GB)`,
  //   rating: `4.3`,
  //   price: `67,999`,
  //   category: `mobiles`,
  //   src: `https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/6/c/5/-original-imagmefcgvntdtha.jpeg?q=70`,
  // },

  // Add more cards as needed
];

export default contacts;
